  - name: Deploy uptime-kuma service
    community.docker.docker_compose:
      project_name: uptime-kuma
      definition:
        version: '3'
        services:
          uptime-kuma:
            restart: always
            ports:
              - 3001:3001
            volumes:
              - uptime-kuma:/app/data
            container_name: uptime-kuma
            image: louislam/uptime-kuma:1
        volumes:
          uptime-kuma:
            external:
              name: uptime-kuma