---

- name: get the sample-app
  shell: git clone https://github.com/K1000KN/terracloud.git
  args:
   creates: "/home/{{ ansible_user }}/terracloud"

- name: Download env file
  get_url:
   url: "{{ env_file }}"
   dest: /home/{{ ansible_user }}/terracloud/.env

- name: chown the folder
  file:
    path: "/home/{{ ansible_user }}/terracloud"
    mode: 0770
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: run the sample-app
  composer:
   command: install
   global_command: false
   working_dir: /home/{{ ansible_user }}/terracloud
  become: false

- name: Run PHP Artisan migrate
  shell: php artisan migrate
  args:
   chdir: /home/{{ ansible_user }}/terracloud

- name: Run PHP Artisan db:seed
  shell: php artisan db:seed
  args:
   chdir: /home/{{ ansible_user }}/terracloud

- name: Run PHP Artisan Serve
  shell: php artisan serve --host=0.0.0.0 &
  args:
   chdir: /home/{{ ansible_user }}/terracloud

