---

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    daemon_reload: yes

- name: Enable remote login to mysql
  lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      backup: yes
  notify: restart mysql deamon