---

packages:
      - php8.1
      - php8.1-fpm
      - openssl
      - php8.1-common
      - php8.1-curl
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-xml
      - php8.1-zip
      - php8.1-bcmath