---

- name: Unarchive tar archive
  unarchive:
    src: https://github.com/traefik/traefik/releases/download/v2.10.7/traefik_v2.10.7_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create a directory if it does not exist
  file:
    path: /home/{{ ansible_user }}/shared
    state: directory
    mode: '0755'

- name: Download traefik yaml
  get_url:
   url: "{{ traefik_file }}"
   dest: /home/{{ ansible_user }}
   owner: "{{ ansible_user }}"
   group: "{{ ansible_user }}"

- name: Download dynamic_conf yaml
  get_url:
   url: "{{ traefik_conf }}"
   dest: /home/{{ ansible_user }}
   owner: "{{ ansible_user }}"
   group: "{{ ansible_user }}"

- name: Run traefik daemon
  command:
   cmd: traefik --configfile=./traefik.yml
   creates: /tmp/traefik.pid
  become: true
