# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC

on:
 workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        run: az login -u ${{secrets.AZURE_USERNAME}} -p ${{secrets.AZURE_PWD}}"
  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
