# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: 
  workflow_dispatch:
  
permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PASQUEFAUTQUECAMARCHE
        run: | 
           export AZURE_SUBSCRIPTION_ID=1eb5e572-df10-47a3-977e-b0ec272641e4
           export AZURE_CLIENT_SECRET=ivk8Q~KltEfLNru3hibuPk2yfzGxKuMU5EP8Eaq6
           export AZURE_CLIENT_ID=f663cd88-759e-4c67-accb-845e91195488
           export AZURE_TENANT_ID=901cb4ca-b862-4029-9306-e5cd0f6d9f86

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
      - name: Echo PASQUEFAUTQUECAMARCHE
        run: echo $AZURE_CREDENTIALS && ls ~/.azure/

