# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: 
  workflow_dispatch:
  
permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.clientId }}","clientSecret":"${{ secrets.clientSecret }}","subscriptionId":"${{ secrets.subscriptionId }}","tenantId":"${{ secrets.tenantId }}"}'
  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
      - name: Echo PASQUEFAUTQUECAMARCHE
        run: echo $AZURE_CREDENTIALS && ls ~/.azure/

