# File: .github/workflows/workflow.yml

name: Run Azure Login

on:
 workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: ./terraform

    steps:

      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
        
      # - name: Azure login
      #   run: az login

      # - name: Terraform init
      #   id: init
      #   run: terraform init

      # - name: Terraform plan
      #   id: plan
      #   run: terraform plan -no-color -input=false
      #   continue-on-error: true

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -input=false

      - name: GitHub Actions Ansible Vault
        uses: taichunmin/github-actions-ansible-vault@v1.0.0
        with:
         vault_key: ${{ secrets.VAULT_KEY }}
         command: |
                  ls /github/home && \
                  ansible-vault decrypt secret.yml

      # - name: ansible playbook
      #   working-directory: ./ansible
      #   run:   |
      #          ansible-playbook init_sqldb.yaml --private-key PRIVATE_KEY_FILE
      #          ansible-playbook init_webapp.yaml --private-key PRIVATE_KEY_FILE
