# File: .github/workflows/workflow.yml

name: Run Azure Login

on:
 workflow_dispatch:

env:
 ACTIONS_RUNNER_DEBUG: true
 ACTIONS_STEP_DEBUG: true

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
        
      - name: Azure login
        run: az login

      - name: Terraform init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false

      - name: GitHub Actions Ansible Vault
        uses: taichunmin/github-actions-ansible-vault@v1.0.0
        with:
         working-directory: ./terraform/ansible
         vault_key: ${{ secrets.VAULT_KEY }}
         command: ansible-vault decrypt secret.yml

      - name: ansible playbook
        working-directory: ./terraform/ansible
        run:   |
               ansible-playbook init_sqldb.yaml --private-key PRIVATE_KEY_FILE
               ansible-playbook init_webapp.yaml --private-key PRIVATE_KEY_FILE
